// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBigGtzjHkshF-flVRoL51LvUduwW6hnpA',
    appId: '1:137233550881:web:d20cc32fbf471483e79d60',
    messagingSenderId: '137233550881',
    projectId: 'football-pro-479a2',
    authDomain: 'football-pro-479a2.firebaseapp.com',
    storageBucket: 'football-pro-479a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzLYXnkgdA-jClLCtl2NX255kgVbA8ZIQ',
    appId: '1:137233550881:android:0515da918475f195e79d60',
    messagingSenderId: '137233550881',
    projectId: 'football-pro-479a2',
    storageBucket: 'football-pro-479a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHYu1bD-Dxsd7fsw9tsgpcPklZpmPssco',
    appId: '1:137233550881:ios:df7a04c04ce6f3d9e79d60',
    messagingSenderId: '137233550881',
    projectId: 'football-pro-479a2',
    storageBucket: 'football-pro-479a2.appspot.com',
    iosClientId: '137233550881-h7cuu6436gleo8s4sbg82ubiql6ts22r.apps.googleusercontent.com',
    iosBundleId: 'com.example.football',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHYu1bD-Dxsd7fsw9tsgpcPklZpmPssco',
    appId: '1:137233550881:ios:1cb14fca5cda6a8de79d60',
    messagingSenderId: '137233550881',
    projectId: 'football-pro-479a2',
    storageBucket: 'football-pro-479a2.appspot.com',
    iosClientId: '137233550881-h9qlsrc1fnpnj7jcf9k2v1urvd770ci2.apps.googleusercontent.com',
    iosBundleId: 'com.example.football.RunnerTests',
  );
}
