// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfmbnkKES9IOMAlUO5JBDcnUv-r0vbDvU',
    appId: '1:456043939616:web:fc0ce54b887c886aa2b945',
    messagingSenderId: '456043939616',
    projectId: 'matchview-a3fb0',
    authDomain: 'matchview-a3fb0.firebaseapp.com',
    storageBucket: 'matchview-a3fb0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcwZ0U4zbGxWVusP11slpwPfkkD370ixs',
    appId: '1:456043939616:android:a122bb90d8f26212a2b945',
    messagingSenderId: '456043939616',
    projectId: 'matchview-a3fb0',
    storageBucket: 'matchview-a3fb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXd1-Npo5YdDHDgXMXyIt6ME_7wU01zdo',
    appId: '1:456043939616:ios:5152d9450340a5eca2b945',
    messagingSenderId: '456043939616',
    projectId: 'matchview-a3fb0',
    storageBucket: 'matchview-a3fb0.appspot.com',
    iosBundleId: 'com.matchview.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXd1-Npo5YdDHDgXMXyIt6ME_7wU01zdo',
    appId: '1:456043939616:ios:86b87ea659a5311aa2b945',
    messagingSenderId: '456043939616',
    projectId: 'matchview-a3fb0',
    storageBucket: 'matchview-a3fb0.appspot.com',
    iosBundleId: 'com.example.football.RunnerTests',
  );
}
