const Map<String, String> en = {
  'txt_login': 'login',
  'txt_sign_up': 'sign up',
  'txt_register': 'register',
  'txt_email': 'email',
  'txt_password': 'password',
  'txt_or': 'or',
  'txt_write_your_email': 'write your email',
  'txt_create_a_password': 'create a password',
  'txt_sign_up_with_google': 'Sign up with Google',
  'txt_write_your_password': 'write your password',
  'txt_sign_in_with_google': 'Sign in with Google',
  'txt_home': 'home',
  'txt_favorites': 'favorites',
  'txt_profile': 'profile',
  'txt_search': 'search',
  'txt_name': 'name',
  'txt_write_your_name': 'write your name',
  'txt_the_list_is_empty_add_your_favorite_team_to_the_list':
      'The list is empty.\nAdd your favorite team to the list',
  'txt_statistic': 'statistic',
  'txt_live': 'live',
};
